### ISSUE TITLE
Millions of followers

### ISSUE THREAD

**Issue by sonhle** [mongodb-labs/socialite#11]
Hi, Thanks for sharing. This is not an issue, but a question. What if a user has a very long list of followers, eg millions of followers like twitter or facebook? How we will deal with it?

**Comment by asya999** [comment]
The config to use is the one that scales best, which is where edges (relationships) are stored separately from nodes (users).  This is discussed in the presentations we've done about this.  Embedding is not a good choice for this type of application for that exact reason.
