### ISSUE TITLE
How can one make this thing running?

### ISSUE THREAD

**Issue by mclate** [mongodb-labs/socialite#9]
According to `building.md` one should "Run `java -jar ./target/socialite-0.0.1-SNAPSHOT.jar server sample-config.yml`", however i wasn't able to find jar file neither in repository nor in google.

How can one start and test this tool?

Thanks.

**Comment by ruhkopf** [comment]
Not sure if this is still useful, but I just noticed, too, that the "building" part is missing in the documentation. You can build with Maven: `mvn install -DskipTests`.

**Comment by asya999** [comment]
Added line how to build to docs building file.
